## Wrangling parks data

### Goals of the Task


Each row in the cultural spaces data set is a Seattle venue such as a cinema, art gallery, theatre or music venue.  

The aim of this task is to remove cultural spaces from the data that we donâ€™t have location information against, plus any spaces that were closed before the period of our cycle hire data sample. Then, using the range of longitude and latitude found in the cycle hire data, you will eliminate cultural spaces that are not located near cycle hire stations. 

After this you will use an aggregation method in pandas to review the number of cultural spaces in your remaining data set, summarizing these venues by neighbourhood and cultural purpose.

#### Step 1 : use pandas to read the cultural spaces csv as a data frame
- import pandas as pd 
- use pandas read_csv to create a culturalspaces data frame 
- ensure you are pointing at the correct file path for the data source (you may have to navigate in your notebook!)

In [1]:
import pandas as pd

In [20]:
df = pd.read_csv('Seattle_Cultural_Space_Inventory.csv')

In [21]:
df

,Name,Phone,URL,Square Feet Total,Neighborhood,Organization Type,Dominant Discipline,Year of Occupation,Rent vs Own,Age of Current Building,...,Constituency over 50% one race,Specific Demographics and Community,Organization Leadership,Organization Artists,Closed Date,Closed?,Address,Location,Latitude,Longitude
0,10 Degrees,NaN,www.10degreesseattle.com,750.0,Capitol Hill,N,Multi-use,2011.0,O,1970.0,...,NaN,NaN,NaN,NaN,NaN,0.0,1312 E Union St,"(47.612905, -122.31477)",47.612905,-122.314770
1,Alki Community Center,NaN,NaN,NaN,Alki,NaN,Community Center,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,5817 SW Stevens St Seattle WA 98116,"(47.577271, -122.407364)",47.577271,-122.407364
2,Calypte Gallery,NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,1107 East Denny Way #A2 Seattle WA 98122,"(47.618587, -122.317818)",47.618587,-122.317818
3,Cassandria Blackmore Studio,NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,1115 East Pike St Seattle WA 98122,"(47.6139358, -122.3174302)",47.613936,-122.317430
4,Dynamic Sound Service,NaN,NaN,NaN,NaN,NaN,Studios,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,Illumination Learning Studio,(206) 789-ARTS,www.ILSKids.com,2500.0,Phinney Ridge,N,Arts/Cultural Training or Education,2013.0,R,1990.0,...,NaN,NaN,NaN,NaN,NaN,0.0,7720 Greenwood Ave N #101 Seattle WA 98103,"(47.68528, -122.354912)",47.685280,-122.354912
940,Serafina,NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,"2043 Eastlake Ave E Seattle, WA 98102","(47.63803, -122.325924)",47.638030,-122.325924
941,Eight and Sand Gallery,(206) 304-0394,www.eightandsand.com,132.0,Georgetown,N,Visual,2013.0,R,1901.0,...,NaN,NaN,NaN,NaN,NaN,0.0,5840 Airport Way S Suite 212 Seattle WA 98108,"(47.550962, -122.318612)",47.550962,-122.318612
942,University of Washington Mary Gates Hall,NaN,NaN,NaN,NaN,NaN,Arts/Cultural Training or Education,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,Seattle WA 98195,"(47.657048, -122.305271)",47.657048,-122.305271
943,Bill & Melinda Gates Foundation Visitor Center,(206) 709-3100,www.gatesvc.org,10000.0,Uptown,Y,Arts/Cultural Administration or Advocacy,2012.0,O,2008.0,...,NaN,NaN,NaN,NaN,NaN,0.0,440 5th Ave. N Seattle 98109,"(47.622541, -122.34748)",47.622541,-122.347480

In [43]:
df = df.dropna(axis=0, subset=['Latitude', 'Longitude'])

In [44]:
df[df['Closed?'] ==1.0]

,Name,Phone,URL,Square Feet Total,Neighborhood,Organization Type,Dominant Discipline,Year of Occupation,Rent vs Own,Age of Current Building,...,Constituency over 50% one race,Specific Demographics and Community,Organization Leadership,Organization Artists,Closed Date,Closed?,Address,Location,Latitude,Longitude
48,Bop Street Records,NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2020-06-01,1.0,2220 NW Market St Seattle WA 98107,"(47.66909, -122.385796)",47.669090,-122.385796
82,Heartland (CLOSED),NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,5306 Roosevelt Way NE Seattle WA 98105,"(47.66739015, -122.3170984)",47.667390,-122.317098
182,Barnes & Noble - Downtown,NaN,NaN,NaN,Downtown,NaN,Literary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,600 Pine St Suite 107 Seattle WA 98101,"(47.61287415, -122.3352762)",47.612874,-122.335276
207,Landmark Guild 45th,NaN,NaN,NaN,NaN,NaN,Cinema,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-06-01,1.0,2115 N 45th St Seattle WA 98103,"(47.66112015, -122.3330128)",47.661120,-122.333013
276,Teatro ZinZanni,(206) 802-0015,www.zinzanni.com/seattle,28000.0,Uptown,Y,Performance,2006.0,R,2006.0,...,NaN,NaN,NaN,NaN,2017-03-05,1.0,222 Mercer St Seattle WA 98109,"(47.6249259, -122.3518443)",47.624926,-122.351844
283,Bell & Reed,NaN,NaN,NaN,Pioneer Square,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,15 Prefontaine Pl. S Suite 510 Seattle WA 98104,"(47.601719, -122.330269)",47.601719,-122.330269
297,Macha Monkey Productions,NaN,NaN,NaN,NaN,NaN,Performance,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-05-31,1.0,2222 2nd Ave #200 Seattle WA 98121,"(47.613483, -122.344756)",47.613483,-122.344756
342,Fetherston Gallery (CLOSED),NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-03-14,1.0,"5701 6th Ave S, Seattle WA 98108","(47.5514664, -122.3283134)",47.551466,-122.328313
346,Eclectic Theater Company,(206) 679-3271,www.eclectictheatercompany.org,900.0,Capitol Hill,Y,Performance,2006.0,R,1910.0,...,NaN,NaN,NaN,NaN,2017-10-31,1.0,1214 10th Ave Seattle WA 98122,"(47.6126561, -122.3191571)",47.612656,-122.319157
372,Seattle Weekly,NaN,NaN,NaN,Pioneer Square,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-10-25,1.0,307 3rd Ave S Second Floor Seattle WA 98104,"(47.599701, -122.33065)",47.599701,-122.330650
377,Comics Dungeon,(206) 545-8373,www.ComicsDungeon.com,1600.0,Wallingford,N,Visual,2012.0,R,1950.0,...,NaN,NaN,NaN,NaN,2020-07-01,1.0,319 NE 45th St Seattle WA 98105,"(47.661356, -122.3248)",47.661356,-122.324800
422,Landmark Seven Gables Theatre,NaN,NaN,NaN,NaN,NaN,Cinema,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-06-01,1.0,911 NE 50th St Seattle WA 98105,"(47.6647555, -122.3177085)",47.664755,-122.317708
526,Massive Monkees Studios,NaN,www.massivemonkees.com,2200.0,Chinatown International District,N,Performance,2013.0,R,1950.0,...,NaN,NaN,NaN,NaN,2020-12-20,1.0,664 S King St Seattle WA 98104,"(47.598602, -122.324135)",47.598602,-122.324135
547,The Josephine and Friends of NW 65th (CLOSED),(206) 543-0065,www.josephinebaker-bonaparte.blogspot.com,NaN,Ballard,Y,Multi-use,NaN,R,1932.0,...,NaN,NaN,NaN,NaN,2015-02-01,1.0,608 NW 65th St Seattle WA 98117,"(47.6762165, -122.3638347)",47.676217,-122.363835
583,Blindfold Gallery (CLOSED),NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2014-12-11,1.0,1718 E Olive Way Seattle WA 98102,"(47.6200267, -122.3227112)",47.620027,-122.322711
592,Studio Current,NaN,NaN,NaN,Capitol Hill,NaN,Multi-use,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-09-30,1.0,1417 10th Ave #C Seattle WA 98122,"(47.613223, -122.319412)",47.613223,-122.319412
593,The Studio of Awesome (CLOSED),NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-11-13,1.0,101 N 85th Street #201 Seattle WA 98103,"(47.69038, -122.3577075)",47.690380,-122.357708
614,Ltd. Art Gallery (CLOSED),(206) 457-2970,www.ltdartgallery.com,1100.0,Capitol Hill,N,Visual,2011.0,R,2008.0,...,NaN,NaN,NaN,NaN,2015-03-01,1.0,307 E Pike St Seattle WA 98122,"(47.6138928, -122.3271174)",47.613893,-122.327117
627,Re-bar,NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2020-06-01,1.0,1114 Howell St Seattle WA 98101,"(47.6167076, -122.3310756)",47.616708,-122.331076
630,The Big Picture,(206) 256-0566,www.thebigpicture.net,4400.0,Belltown,N,Cinema,1998.0,NaN,1950.0,...,NaN,NaN,NaN,NaN,2020-05-01,1.0,2505 1st Ave Seattle WA 98121,"(47.6146778, -122.3492477)",47.614678,-122.349248
673,University of Washington Physics Astronomy Rea...,NaN,NaN,NaN,NaN,NaN,Education,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,3910 15th Ave NE Seattle WA 98105,"(47.65408, -122.312135)",47.654080,-122.312135
681,Art/Not Terminal Gallery,(206) 233-0680,www.antgallery.org,3280.0,South Lake Union,Y,Visual,1993.0,R,1920.0,...,NaN,NaN,NaN,NaN,2016-05-31,1.0,2045 Westlake Ave Seattle WA 98121,"(47.6158592, -122.338453)",47.615859,-122.338453
726,New Foundation,(206) 512-7247,www.thenewest.org,1800.0,Central District,Y,Visual,2012.0,R,1919.0,...,NaN,NaN,NaN,NaN,2016-05-01,1.0,312 2nd Ave South Seattle WA,"(47.599537, -122.331177)",47.599537,-122.331177
798,Storefronts Seattle/Shunpike,(206) 905-1026,www.shunpike.org,26600.0,Belltown,Y,Multi-use,2007.0,R,1889.0,...,NaN,NaN,NaN,NaN,NaT,1.0,2324 1st Ave # 112 Seattle WA 98121,"(47.6139909, -122.3472372)",47.613991,-122.347237
802,The White Rabbit (CLOSED),NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-12-13,1.0,513 N 36th St Seattle WA 98103,"(47.6513564, -122.3515985)",47.651356,-122.351598
805,Pilchuck Glass School Office (CLOSED/MOVED),NaN,NaN,NaN,NaN,NaN,Arts/Cultural Administration or Advocacy,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-10-14,1.0,430 Yale Ave N Seattle WA 98109,"(47.6228012, -122.3302142)",47.622801,-122.330214
857,Hugo House,(206) 322-7030,www.hugohouse.org,11000.0,Capitol Hill,Y,Literary,2004.0,R,1900.0,...,NaN,NaN,NaN,NaN,2016-05-15,1.0,1634 11th Ave Seattle WA 98122,"(47.6162473, -122.3178798)",47.616247,-122.317880
878,Seattle ArtREsource (CLOSED),(206) 838-2695,www.seattleartresource.com,2500.0,Pioneer Square,N,Visual,2006.0,O,1905.0,...,NaN,NaN,NaN,NaN,2015-03-28,1.0,625 1st Ave #200 Seattle WA 98104,"(47.6024431, -122.3344096)",47.602443,-122.334410
917,Harvard Exit Theatre (CLOSED),NaN,NaN,NaN,NaN,NaN,Cinema,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2015-01-31,1.0,807 E Roy St Seattle WA 98102,"(47.6250082, -122.3215822)",47.625008,-122.321582
919,Mind Unwind Foundation,(206) 829-9128,www.mindunwind.org,2000.0,Admiral,Y,Arts/Cultural Training or Education,2011.0,R,2011.0,...,NaN,NaN,NaN,NaN,NaT,1.0,2206A California Ave SW Seattle WA 98116,"(47.583717, -122.386024)",47.583717,-122.386024
937,New City Theater,(206) 271-4430,www.newcitytheater.org,1950.0,Central District,Y,Performance,2008.0,R,1935.0,...,NaN,NaN,NaN,NaN,NaT,1.0,1404 18th Ave Seattle WA 98122,"(47.6131012, -122.3086934)",47.613101,-122.308693

In [45]:
df['Closed Date']=pd.to_datetime(df['Closed Date'])

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 903 entries, 0 to 943
Data columns (total 37 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Name                                                         903 non-null    object
 1   Phone                                                        457 non-null    object
 2   URL                                                          460 non-null    object
 3   Square Feet Total                                            444 non-null    float64
 4   Neighborhood                                                 493 non-null    object
 5   Organization Type                                            481 non-null    object
 6   Dominant Discipline                                          864 non-null    object
 7   Year of Occupation                                           456 non-null    float64
 8   Rent vs Own                                                  459 non-null    object
 9   Age of Current Building                                      431 non-null    float64
 10  Length of Lease (Date)                                       349 non-null    object
 11   Year Organization Founded                                   453 non-null    float64
 12  Number of Past Facilities                                    447 non-null    float64
 13  Stages and Theaters                                          442 non-null    float64
 14  Stage & Theater Seats                                        382 non-null    float64
 15  Gallery Space                                                446 non-null    object
 16  Gallery Square Feet                                          356 non-null    float64
 17  ADA Compliant                                                432 non-null    object
 18  Available Parking                                            366 non-null    float64
 19  Street Presence                                              453 non-null    object
 20  Rental Space                                                 449 non-null    object
 21  Alcohol Sales                                                457 non-null    object
 22  Organization Mission                                         40 non-null     object
 23  Funded by A&C                                                455 non-null    object
 24  Funded by 4Culture                                           25 non-null     object
 25  Stability Index (5=very stable, 1=very uncertain)            456 non-null    float64
 26  Control Index (5=very in control, 1 = very out of control)   40 non-null     float64
 27  Constituency over 50% one race                               38 non-null     object
 28  Specific Demographics and Community                          38 non-null     object
 29  Organization Leadership                                      16 non-null     object
 30  Organization Artists                                         15 non-null     object
 31  Closed Date                                                  24 non-null     datetime64[ns]
 32  Closed?                                                      826 non-null    float64
 33  Address                                                      900 non-null    object
 34  Location                                                     903 non-null    object
 35  Latitude                                                     903 non-null    float64
 36  Longitude                                                    903 non-null    float64
dtypes: datetime64[ns](1), float64(14), object(22)
memory usage: 268.1+ KB

In [47]:
df[df['Closed?'] ==1.0]

,Name,Phone,URL,Square Feet Total,Neighborhood,Organization Type,Dominant Discipline,Year of Occupation,Rent vs Own,Age of Current Building,...,Constituency over 50% one race,Specific Demographics and Community,Organization Leadership,Organization Artists,Closed Date,Closed?,Address,Location,Latitude,Longitude
48,Bop Street Records,NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2020-06-01,1.0,2220 NW Market St Seattle WA 98107,"(47.66909, -122.385796)",47.669090,-122.385796
82,Heartland (CLOSED),NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,5306 Roosevelt Way NE Seattle WA 98105,"(47.66739015, -122.3170984)",47.667390,-122.317098
182,Barnes & Noble - Downtown,NaN,NaN,NaN,Downtown,NaN,Literary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,600 Pine St Suite 107 Seattle WA 98101,"(47.61287415, -122.3352762)",47.612874,-122.335276
207,Landmark Guild 45th,NaN,NaN,NaN,NaN,NaN,Cinema,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-06-01,1.0,2115 N 45th St Seattle WA 98103,"(47.66112015, -122.3330128)",47.661120,-122.333013
276,Teatro ZinZanni,(206) 802-0015,www.zinzanni.com/seattle,28000.0,Uptown,Y,Performance,2006.0,R,2006.0,...,NaN,NaN,NaN,NaN,2017-03-05,1.0,222 Mercer St Seattle WA 98109,"(47.6249259, -122.3518443)",47.624926,-122.351844
283,Bell & Reed,NaN,NaN,NaN,Pioneer Square,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,15 Prefontaine Pl. S Suite 510 Seattle WA 98104,"(47.601719, -122.330269)",47.601719,-122.330269
297,Macha Monkey Productions,NaN,NaN,NaN,NaN,NaN,Performance,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-05-31,1.0,2222 2nd Ave #200 Seattle WA 98121,"(47.613483, -122.344756)",47.613483,-122.344756
342,Fetherston Gallery (CLOSED),NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-03-14,1.0,"5701 6th Ave S, Seattle WA 98108","(47.5514664, -122.3283134)",47.551466,-122.328313
346,Eclectic Theater Company,(206) 679-3271,www.eclectictheatercompany.org,900.0,Capitol Hill,Y,Performance,2006.0,R,1910.0,...,NaN,NaN,NaN,NaN,2017-10-31,1.0,1214 10th Ave Seattle WA 98122,"(47.6126561, -122.3191571)",47.612656,-122.319157
372,Seattle Weekly,NaN,NaN,NaN,Pioneer Square,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-10-25,1.0,307 3rd Ave S Second Floor Seattle WA 98104,"(47.599701, -122.33065)",47.599701,-122.330650
377,Comics Dungeon,(206) 545-8373,www.ComicsDungeon.com,1600.0,Wallingford,N,Visual,2012.0,R,1950.0,...,NaN,NaN,NaN,NaN,2020-07-01,1.0,319 NE 45th St Seattle WA 98105,"(47.661356, -122.3248)",47.661356,-122.324800
422,Landmark Seven Gables Theatre,NaN,NaN,NaN,NaN,NaN,Cinema,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2017-06-01,1.0,911 NE 50th St Seattle WA 98105,"(47.6647555, -122.3177085)",47.664755,-122.317708
526,Massive Monkees Studios,NaN,www.massivemonkees.com,2200.0,Chinatown International District,N,Performance,2013.0,R,1950.0,...,NaN,NaN,NaN,NaN,2020-12-20,1.0,664 S King St Seattle WA 98104,"(47.598602, -122.324135)",47.598602,-122.324135
547,The Josephine and Friends of NW 65th (CLOSED),(206) 543-0065,www.josephinebaker-bonaparte.blogspot.com,NaN,Ballard,Y,Multi-use,NaN,R,1932.0,...,NaN,NaN,NaN,NaN,2015-02-01,1.0,608 NW 65th St Seattle WA 98117,"(47.6762165, -122.3638347)",47.676217,-122.363835
583,Blindfold Gallery (CLOSED),NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2014-12-11,1.0,1718 E Olive Way Seattle WA 98102,"(47.6200267, -122.3227112)",47.620027,-122.322711
592,Studio Current,NaN,NaN,NaN,Capitol Hill,NaN,Multi-use,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-09-30,1.0,1417 10th Ave #C Seattle WA 98122,"(47.613223, -122.319412)",47.613223,-122.319412
593,The Studio of Awesome (CLOSED),NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-11-13,1.0,101 N 85th Street #201 Seattle WA 98103,"(47.69038, -122.3577075)",47.690380,-122.357708
614,Ltd. Art Gallery (CLOSED),(206) 457-2970,www.ltdartgallery.com,1100.0,Capitol Hill,N,Visual,2011.0,R,2008.0,...,NaN,NaN,NaN,NaN,2015-03-01,1.0,307 E Pike St Seattle WA 98122,"(47.6138928, -122.3271174)",47.613893,-122.327117
627,Re-bar,NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2020-06-01,1.0,1114 Howell St Seattle WA 98101,"(47.6167076, -122.3310756)",47.616708,-122.331076
630,The Big Picture,(206) 256-0566,www.thebigpicture.net,4400.0,Belltown,N,Cinema,1998.0,NaN,1950.0,...,NaN,NaN,NaN,NaN,2020-05-01,1.0,2505 1st Ave Seattle WA 98121,"(47.6146778, -122.3492477)",47.614678,-122.349248
673,University of Washington Physics Astronomy Rea...,NaN,NaN,NaN,NaN,NaN,Education,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,1.0,3910 15th Ave NE Seattle WA 98105,"(47.65408, -122.312135)",47.654080,-122.312135
681,Art/Not Terminal Gallery,(206) 233-0680,www.antgallery.org,3280.0,South Lake Union,Y,Visual,1993.0,R,1920.0,...,NaN,NaN,NaN,NaN,2016-05-31,1.0,2045 Westlake Ave Seattle WA 98121,"(47.6158592, -122.338453)",47.615859,-122.338453
726,New Foundation,(206) 512-7247,www.thenewest.org,1800.0,Central District,Y,Visual,2012.0,R,1919.0,...,NaN,NaN,NaN,NaN,2016-05-01,1.0,312 2nd Ave South Seattle WA,"(47.599537, -122.331177)",47.599537,-122.331177
798,Storefronts Seattle/Shunpike,(206) 905-1026,www.shunpike.org,26600.0,Belltown,Y,Multi-use,2007.0,R,1889.0,...,NaN,NaN,NaN,NaN,NaT,1.0,2324 1st Ave # 112 Seattle WA 98121,"(47.6139909, -122.3472372)",47.613991,-122.347237
802,The White Rabbit (CLOSED),NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-12-13,1.0,513 N 36th St Seattle WA 98103,"(47.6513564, -122.3515985)",47.651356,-122.351598
805,Pilchuck Glass School Office (CLOSED/MOVED),NaN,NaN,NaN,NaN,NaN,Arts/Cultural Administration or Advocacy,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2016-10-14,1.0,430 Yale Ave N Seattle WA 98109,"(47.6228012, -122.3302142)",47.622801,-122.330214
857,Hugo House,(206) 322-7030,www.hugohouse.org,11000.0,Capitol Hill,Y,Literary,2004.0,R,1900.0,...,NaN,NaN,NaN,NaN,2016-05-15,1.0,1634 11th Ave Seattle WA 98122,"(47.6162473, -122.3178798)",47.616247,-122.317880
878,Seattle ArtREsource (CLOSED),(206) 838-2695,www.seattleartresource.com,2500.0,Pioneer Square,N,Visual,2006.0,O,1905.0,...,NaN,NaN,NaN,NaN,2015-03-28,1.0,625 1st Ave #200 Seattle WA 98104,"(47.6024431, -122.3344096)",47.602443,-122.334410
917,Harvard Exit Theatre (CLOSED),NaN,NaN,NaN,NaN,NaN,Cinema,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2015-01-31,1.0,807 E Roy St Seattle WA 98102,"(47.6250082, -122.3215822)",47.625008,-122.321582
919,Mind Unwind Foundation,(206) 829-9128,www.mindunwind.org,2000.0,Admiral,Y,Arts/Cultural Training or Education,2011.0,R,2011.0,...,NaN,NaN,NaN,NaN,NaT,1.0,2206A California Ave SW Seattle WA 98116,"(47.583717, -122.386024)",47.583717,-122.386024
937,New City Theater,(206) 271-4430,www.newcitytheater.org,1950.0,Central District,Y,Performance,2008.0,R,1935.0,...,NaN,NaN,NaN,NaN,NaT,1.0,1404 18th Ave Seattle WA 98122,"(47.6131012, -122.3086934)",47.613101,-122.308693

In [59]:
closed_places = df[df['Closed Date'] < '2014-09-30'].index

In [60]:
df.drop(closed_places, inplace=True)

In [62]:
df.drop(['index'], axis='columns', inplace=True)

In [52]:
df = df.reset_index()

In [65]:
df

,Name,Phone,URL,Square Feet Total,Neighborhood,Organization Type,Dominant Discipline,Year of Occupation,Rent vs Own,Age of Current Building,...,Constituency over 50% one race,Specific Demographics and Community,Organization Leadership,Organization Artists,Closed Date,Closed?,Address,Location,Latitude,Longitude
0,10 Degrees,NaN,www.10degreesseattle.com,750.0,Capitol Hill,N,Multi-use,2011.0,O,1970.0,...,NaN,NaN,NaN,NaN,NaT,0.0,1312 E Union St,"(47.612905, -122.31477)",47.612905,-122.314770
1,Alki Community Center,NaN,NaN,NaN,Alki,NaN,Community Center,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,0.0,5817 SW Stevens St Seattle WA 98116,"(47.577271, -122.407364)",47.577271,-122.407364
2,Calypte Gallery,NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,0.0,1107 East Denny Way #A2 Seattle WA 98122,"(47.618587, -122.317818)",47.618587,-122.317818
3,Cassandria Blackmore Studio,NaN,NaN,NaN,NaN,NaN,Visual,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,0.0,1115 East Pike St Seattle WA 98122,"(47.6139358, -122.3174302)",47.613936,-122.317430
4,Eritrean Association in Greater Seattle,NaN,NaN,NaN,NaN,NaN,Community Center,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,0.0,1528 Valentine Pl S Seattle WA 98144,"(47.58879805, -122.3070771)",47.588798,-122.307077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898,Illumination Learning Studio,(206) 789-ARTS,www.ILSKids.com,2500.0,Phinney Ridge,N,Arts/Cultural Training or Education,2013.0,R,1990.0,...,NaN,NaN,NaN,NaN,NaT,0.0,7720 Greenwood Ave N #101 Seattle WA 98103,"(47.68528, -122.354912)",47.685280,-122.354912
899,Serafina,NaN,NaN,NaN,NaN,NaN,Music,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,0.0,"2043 Eastlake Ave E Seattle, WA 98102","(47.63803, -122.325924)",47.638030,-122.325924
900,Eight and Sand Gallery,(206) 304-0394,www.eightandsand.com,132.0,Georgetown,N,Visual,2013.0,R,1901.0,...,NaN,NaN,NaN,NaN,NaT,0.0,5840 Airport Way S Suite 212 Seattle WA 98108,"(47.550962, -122.318612)",47.550962,-122.318612
901,University of Washington Mary Gates Hall,NaN,NaN,NaN,NaN,NaN,Arts/Cultural Training or Education,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,0.0,Seattle WA 98195,"(47.657048, -122.305271)",47.657048,-122.305271
902,Bill & Melinda Gates Foundation Visitor Center,(206) 709-3100,www.gatesvc.org,10000.0,Uptown,Y,Arts/Cultural Administration or Advocacy,2012.0,O,2008.0,...,NaN,NaN,NaN,NaN,NaT,0.0,440 5th Ave. N Seattle 98109,"(47.622541, -122.34748)",47.622541,-122.347480

#### Step 2 : drop unusuable rows

- first, using the pandas dropna() method, remove from the culturalspaces data frame any rows which have null in either the Longitude or Latitude columns 
- next, drop rows of culturalspaces which were closed prior to the first date in our cycle hire data (Oct 2014) using any pandas filter approach 
- reset the index of your culturalspaces data frame after dropping rows 


https://www.geeksforgeeks.org/ways-to-filter-pandas-dataframe-by-column-values/

#### Step 3 : create a data frame from the cycle hire station data to get the ranges of longitude and latitude 

- use pandas read_csv to create a second data frame from seattle_cycles_station.csv file 
- use max() and min() to identify the range of longitude and latitude values in the cycle station data

In [66]:
stn=pd.read_csv('Seattle_cycles_station.csv')

In [69]:
stn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   station_id         58 non-null     object
 1   name               58 non-null     object
 2   lat                58 non-null     float64
 3   long               58 non-null     float64
 4   install_date       58 non-null     object
 5   install_dockcount  58 non-null     int64
 6   modification_date  17 non-null     object
 7   current_dockcount  58 non-null     int64
 8   decommission_date  4 non-null      object
dtypes: float64(2), int64(2), object(5)
memory usage: 4.2+ KB

In [71]:
stn.describe()

             lat        long  install_dockcount  current_dockcount
count  58.000000   58.000000          58.000000          58.000000
mean   47.624796 -122.327242          17.586207          16.517241
std     0.019066    0.014957           3.060985           5.117021
min    47.598488 -122.355230          12.000000           0.000000
25%    47.613239 -122.338735          16.000000          16.000000
50%    47.618591 -122.328206          18.000000          18.000000
75%    47.627712 -122.316691          18.000000          18.000000
max    47.666145 -122.284119          30.000000          26.000000

In [89]:
stn['lat'].max()

47.666145

In [90]:
stn['lat'].min()

47.598488

In [91]:
stn['long'].max()

-122.284119

In [92]:
stn['long'].min()

-122.35523

In [93]:
stn

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
0,BT-01,3rd Ave & Broad St,47.618418,-122.350964,10/13/2014,18,NaN,18,NaN
1,BT-03,2nd Ave & Vine St,47.615829,-122.348564,10/13/2014,16,NaN,16,NaN
2,BT-04,6th Ave & Blanchard St,47.616094,-122.341102,10/13/2014,16,NaN,16,NaN
3,BT-05,2nd Ave & Blanchard St,47.613110,-122.344208,10/13/2014,14,NaN,14,NaN
4,CBD-03,7th Ave & Union St,47.610731,-122.332447,10/13/2014,20,NaN,20,NaN
5,CBD-04,Union St & 4th Ave,47.609221,-122.335596,7/27/2015,18,NaN,18,NaN
6,CBD-05,1st Ave & Marion St,47.604058,-122.335800,10/13/2014,20,NaN,20,NaN
7,CBD-06,2nd Ave & Spring St,47.605950,-122.335768,10/13/2014,20,11/9/2015,18,NaN
8,CBD-07,City Hall / 4th Ave & James St,47.603509,-122.330409,10/13/2014,20,NaN,20,NaN
9,CBD-13,2nd Ave & Pine St,47.610185,-122.339641,10/13/2014,18,NaN,18,NaN
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016
11,CH-01,Summit Ave & E Denny Way,47.618633,-122.325249,10/13/2014,16,NaN,16,NaN
12,CH-02,E Harrison St & Broadway Ave E,47.622063,-122.321251,10/13/2014,18,2/24/2015,20,NaN
13,CH-03,Summit Ave E & E Republican St,47.623367,-122.325279,10/13/2014,16,NaN,16,NaN
14,CH-05,15th Ave E & E Thomas St,47.620712,-122.312805,10/13/2014,16,NaN,16,NaN
15,CH-06,12th Ave & E Denny Way,47.618549,-122.317017,10/13/2014,16,NaN,16,NaN
16,CH-07,E Pine St & 16th Ave,47.615330,-122.311752,10/13/2014,18,NaN,18,NaN
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN
18,CH-09,Harvard Ave & E Pine St,47.615517,-122.322083,10/13/2014,16,NaN,16,NaN
19,CH-12,Bellevue Ave & E Pine St,47.615456,-122.326729,10/13/2014,18,NaN,14,NaN
20,CH-15,12th Ave & E Mercer St,47.624142,-122.316811,10/13/2014,16,NaN,16,NaN
21,DPD-01,9th Ave N & Mercer St,47.624298,-122.339617,10/13/2014,18,NaN,18,NaN
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN
23,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,47.627643,-122.332576,10/13/2014,12,3/27/2015,16,NaN
24,EL-03,E Blaine St & Fairview Ave E,47.634831,-122.326634,10/13/2014,18,NaN,18,NaN
25,EL-05,Eastlake Ave E & E Allison St,47.649090,-122.322983,10/13/2014,18,NaN,18,NaN
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016
27,FH-04,Seattle University / E Columbia St & 12th Ave,47.609239,-122.316651,10/13/2014,20,NaN,20,NaN
28,ID-04,6th Ave S & S King St,47.598488,-122.326412,10/13/2014,16,NaN,16,NaN
29,PS-04,Occidental Park / Occidental Ave S & S Washing...,47.600757,-122.332946,10/13/2014,18,NaN,18,NaN
30,PS-05,King Street Station Plaza / 2nd Ave Extension ...,47.598994,-122.329684,10/13/2014,18,NaN,18,NaN
31,SLU-01,REI / Yale Ave N & John St,47.619859,-122.330304,10/13/2014,18,2/24/2015,20,NaN
32,SLU-02,Dexter Ave N & Aloha St,47.627735,-122.342232,10/13/2014,18,NaN,18,NaN
33,SLU-04,Republican St & Westlake Ave N,47.623165,-122.338203,10/13/2014,18,NaN,18,NaN
34,SLU-07,PATH / 9th Ave & Westlake Ave,47.618320,-122.338913,10/13/2014,18,NaN,18,NaN
35,SLU-15,Westlake Ave & 6th Ave,47.613628,-122.337341,10/13/2014,12,3/13/2015,20,NaN
36,SLU-16,Pine St & 9th Ave,47.613715,-122.331777,10/13/2014,20,NaN,20,NaN
37,SLU-17,Lake Union Park / Valley St & Boren Ave N,47.626041,-122.335831,10/13/2014,18,2/23/2015,16,NaN
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016
39,SLU-19,Key Arena / 1st Ave N & Harrison St,47.622277,-122.355230,10/13/2014,12,3/4/2015,16,NaN
40,SLU-20,Terry Ave & Stewart St,47.616260,-122.333815,6/12/2015,20,NaN,20,NaN
41,SLU-21,Mercer St & 9th Ave N,47.624769,-122.339408,9/15/2015,20,NaN,20,NaN
42,UD-01,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,47.666145,-122.301491,10/13/2014,18,NaN,18,NaN
43,UD-02,NE 42nd St & University Way NE,47.658288,-122.313334,10/13/2014,18,NaN,18,NaN
44,UD-04,12th Ave & NE Campus Pkwy,47.656395,-122.315620,10/13/2014,16,NaN,16,NaN
45,UD-07,NE 47th St & 12th Ave NE,47.663143,-122.315086,10/13/2014,16,NaN,16,NaN
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015
47,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,47.659756,-122.310402,10/13/2014,12,2/20/2015,14,NaN
48,UW-04,15th Ave NE & NE 40th St,47.655590,-122.311890,10/13/2014,18,2/20/2015,16,NaN
49,UW-06,UW Engineering Library / E Stevens Way NE & Je...,47.654613,-122.304863,10/13/2014,12,2/20/2015,14,NaN
50,UW-07,UW Intramural Activities Building,47.653713,-122.302162,10/13/2014,20,2/20/2015,14,NaN
51,UW-10,UW Magnuson Health Sciences Center Rotunda / C...,47.650725,-122.311188,10/13/2014,16,NaN,16,NaN
52,WF-01,Pier 69 / Alaskan Way & Clay St,47.614315,-122.354093,10/13/2014,18,NaN,24,NaN
53,WF-04,Seattle Aquarium / Alaskan Way S & Elliott Bay...,47.607702,-122.341650,10/13/2014,18,NaN,18,NaN
54,CH-16,Broadway and E Denny Way,47.618640,-122.320777,3/18/2016,18,NaN,18,NaN
55,SLU-22,Thomas St & 5th Ave N,47.620879,-122.347377,7/3/2016,18,NaN,18,NaN
56,UW-11,NE Pacific St/UW Medical Center,47.649952,-122.306263,10/29/2015,16,NaN,16,NaN
57,WF-03,Pier 66 / Alaskan Way & Bell St,47.611370,-122.348702,8/9/2016,18,NaN,18,NaN

In [102]:
lower_bound_long = stn['long'].min()
upper_bound_long = stn['long'].max()
lower_bound_lat = stn['lat'].min()
upper_bound_lat = stn['lat'].max()
cultural_spaces_inrange=df[(df['Longitude'] >= lower_bound_long) &
                           (df['Longitude'] <= upper_bound_long) &
                           (df['Latitude'] >= lower_bound_lat) &
                           (df['Latitude'] <= upper_bound_lat)]
cultural_spaces_inrange.reset_index(drop = True , inplace=True)

In [105]:
cultural_spaces_inrange.describe()

,Square Feet Total,Year of Occupation,Age of Current Building,Year Organization Founded,Number of Past Facilities,Stages and Theaters,Stage & Theater Seats,Gallery Square Feet,Available Parking,"Stability Index (5=very stable, 1=very uncertain)","Control Index (5=very in control, 1 = very out of control)",Closed?,Latitude,Longitude
count,233.000000,238.000000,224.000000,236.000000,233.000000,233.000000,200.000000,192.000000,193.000000,239.000000,16.000000,432.000000,488.000000,488.000000
mean,21240.690987,1995.504202,1939.540179,1983.792373,1.154506,1.000000,186.180000,2734.380208,22.487047,4.037657,3.750000,0.057870,47.620640,-122.327429
std,57319.955515,24.169889,35.459295,30.911185,1.362107,6.334089,480.320985,16158.339501,104.593962,1.185807,1.238278,0.233769,0.020541,0.014570
min,90.000000,1891.000000,1889.000000,1861.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,47.598572,-122.355169
25%,1500.000000,1992.000000,1910.000000,1973.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,2.750000,0.000000,47.605016,-122.337033
50%,4000.000000,2004.500000,1927.000000,1993.000000,1.000000,0.000000,0.000000,100.000000,0.000000,4.000000,4.000000,0.000000,47.614140,-122.329938
75%,11300.000000,2010.000000,1962.000000,2006.000000,2.000000,1.000000,160.000000,900.000000,2.000000,5.000000,5.000000,0.000000,47.624036,-122.317245
max,400000.000000,2020.000000,2014.000000,2020.000000,7.000000,96.000000,3500.000000,210000.000000,1000.000000,5.000000,5.000000,1.000000,47.665938,-122.285450

#### step 4: drop rows which are outside of the cycle hire data range 

- use any pandas filter method to retain rows in the culturalspaces dataframe which are inside the relevant long/lat range of the cycle hire stations 
- reset the index of your culturalspaces dataframe after dropping rows

#### step 5: simplify and fill gaps in location using python text analysis methods 

this data is quite text heavy, so you will now use methods you encountered in topic 8 to process the data 

- simplify the cultural space category by using any  pandas string method to keep the first word of the Dominant Discipline column, creating a new column 'purpose'
(eg 'Arts/Cultural Training or Education' will become simply 'Arts' in the purpose column )

- using a similar method, simplify the neighbourhood column, creating a neighbourhood_clean column, and amend any typos you see 
(eg 'University District and Laurelhurst/Sand Point' will be classed as 'University District') 

- fill in any gaps in the neighbourhood_clean column as 'unknown neighbourhood'

#### step 6: summarise the cultural spaces by neighbourhood and purpose 

- use the pandas group_by() method to summarise the number of spaces by (known) neighbourhood and cultural purpose